new service
mipt-backend-academy-winter-2023/team-3 pull request #13
Opened 2023-10-04 16:24 UTC by mukhametgalin

2023-10-15 21:48 UTC, stackflow requested changes

2023-10-15 21:48 UTC, stackflow commented on photo/src/main/scala/api/HttpRoutes.scala
> +        } yield (nodeId)).either.map {
А где проверка на размер файла?:
```
2. К дому или перекрестку можно добавить одно фото в формате jpeg до 10 Мбайт...
```

2023-10-15 21:48 UTC, stackflow commented on docs/api/photo.yaml
> +                "400":
Если файл слишком большой (> 10MB), то кажется больше подойдет "422 Unprocessable Entity"

2023-10-15 21:48 UTC, stackflow commented on docker-compose/docker-compose.yml
> +  # database:
Это все нужно раскомментировать, чтобы все компоненты работали

2023-10-15 21:48 UTC, stackflow commented on docker-compose/docker-compose.yml
> +      - "8084"
Для чего нужен `expose`, кажется `ports` достаточно, чтобы дать доступ вне контейнера?

2023-10-15 21:48 UTC, stackflow commented on build.sbt
> +  )
Лучше вернуть перевод строки в конце файла

2023-10-15 21:48 UTC, stackflow commented on docs/api/photo.yaml
> +                    type: string
`No new line at the end of file`

2023-10-15 21:48 UTC, stackflow commented on photo/src/main/resources/application.conf
> +  http-service-config = {
Постфикс `-config` кажется лишним, у нас весь этот файл является конфигом

2023-10-15 21:48 UTC, stackflow commented on photo/src/main/resources/application.conf
> +    port = 8084
Вынести в `.env` переменные, как это сделано для других модулей

2023-10-15 21:48 UTC, stackflow commented on build.sbt
> +  )
Кажется на хватает настроек для `sbt-assembly`?

2023-10-17 16:39 UTC, mukhametgalin commented on docs/api/photo.yaml
> +                "400":
добавил

2023-10-17 16:46 UTC, mukhametgalin commented on docker-compose/docker-compose.yml
> +  # database:
исправил

2023-10-17 16:46 UTC, mukhametgalin commented on docker-compose/docker-compose.yml
> +      - "8084"
исправил

2023-10-17 16:46 UTC, mukhametgalin commented on docs/api/photo.yaml
> +                    type: string
исправил

2023-10-17 16:53 UTC, mukhametgalin commented on photo/src/main/resources/application.conf
> +  http-service-config = {
исправил

2023-10-17 16:53 UTC, mukhametgalin commented on photo/src/main/resources/application.conf
> +    port = 8084
исправил

2023-10-18 19:49 UTC, stackflow commented on compose.yaml
> +      - "${ROUTING_HTTP_PORT}:${ROUTING_HTTP_PORT}"
`${PHOTO_HTTP_PORT}`

2023-10-18 19:49 UTC, stackflow commented on docs/api/photo.yaml
> +                    image/png:
Почему `image/png`?
```
К дому или перекрестку можно добавить одно фото в формате jpeg
```
 Вроде `jpeg` в задании?

2023-10-18 19:49 UTC, stackflow commented on docs/api/photo.yaml
> +                "422":
Кажется я не туда коммент написал - нужно в метод `upload` добавить `422` ошибку
Ты тоже следи за моими комментариями)

2023-10-18 19:49 UTC, stackflow commented on project/Dependencies.scala
> +    override def dependencies: Seq[ModuleID] = Seq(zio, pureconfig, circe).flatten
Для чего `circe` в зависимостях?

2023-10-18 20:21 UTC, stackflow commented on docs/api/photo.yaml
> +        UserData:
Это где используется?

2023-10-19 14:00 UTC, mukhametgalin commented on compose.yaml
> +      - "${ROUTING_HTTP_PORT}:${ROUTING_HTTP_PORT}"
поправил

2023-10-23 18:50 UTC, stackflow reviewed
Надо добавить `HOWTO.md` строку с описанием нового сервиса

2023-11-08 08:43 UTC, stackflow commented on photo/src/main/scala/api/HttpRoutes.scala
> +  def getPath(x: String) = Paths.get(s"/${x}file")
Писать файлы в корневую директорию файловой системы - плохая практика
Исправлять не нужно, просто подсветил
В идеале задавать путь куда сохраняются файлы через конфиг

2023-11-08 08:43 UTC, stackflow commented on photo/src/main/scala/api/HttpRoutes.scala
> +              ).addHeader("content-type", "image/jpeg")
`headers` можно напрямую в `Response` добавить:
```
Response(
  status = Status.Ok,
  headers = Headers(
    Header("Content-Type", "image/jpeg"),
    Header("Content-Length", Files.size(path).toString)
  ),
  body = Body.fromFile(new File(path.toAbsolutePath.toString))
)
```

2023-11-08 08:43 UTC, stackflow commented on photo/src/main/scala/api/HttpRoutes.scala
> +                body = Body.fromFile(new File(path.toAbsolutePath.toString)),
`Body.fromFile` не очень правильное решение, т.к. оно приводит к загрузке всего файла в память `JVM` и возможны ошибки типа: `java.lang.OutOfMemoryError: Java heap space`
Нужно использовать `Body.fromStream`, в качестве параметра передавать `ZStream.fromFile`, тогда файл будет частями передаваться клиенту, без полной загрузки в память

2023-11-08 08:43 UTC, stackflow commented on photo/src/main/scala/config/Config.scala
> +                             host: String,
Хост читается из конфига, но нигде не используется?

2023-11-12 12:41 UTC, mukhametgalin commented on photo/src/main/scala/api/HttpRoutes.scala
> +                body = Body.fromFile(new File(path.toAbsolutePath.toString)),
поправил

2023-11-12 12:43 UTC, mukhametgalin commented on photo/src/main/scala/api/HttpRoutes.scala
> +              ).addHeader("content-type", "image/jpeg")
поправил

2023-11-12 13:04 UTC, mukhametgalin commented on photo/src/main/scala/config/Config.scala
> +                             host: String,
поправил

2023-11-12 13:04 UTC, mukhametgalin commented on photo/src/main/scala/api/HttpRoutes.scala
> +  def getPath(x: String) = Paths.get(s"/${x}file")
ок

2023-11-12 18:07 UTC, stackflow approved these changes

2023-11-12 18:08 UTC, stackflow commented
2/3

- [x] Определяем API нового сервиса через openapi
- [x] К дому или перекрестку можно добавить одно фото в формате jpeg до 10 Мбайт. Эндпоинт должен брать фотку в теле запроса и параметр с идентификатором узла. Обработка запроса должна быть ленивым, изображение не буфферизуется при принятии запроса.
- [x] Фотки складываем в файлы в папочке
- [x] Фотку можно получить по идентификатору узла

[В этом PR](https://github.com/mipt-backend-academy-winter-2023/team-3/pull/17/files) раньше были исправлены ошибки, а так все норм

2023-11-12 18:08 UTC, closed without merging