Homework jpeg validation
mipt-backend-academy-winter-2023/team-3 pull request #15
Opened 2023-10-11 18:36 UTC by mukhametgalin

2023-11-15 20:43 UTC, stackflow requested changes
Нужно немного переделать
Я уже вмержил предыдущее ДЗ от другого студента, поэтому сервис для загрузки картинок у нас теперь `Image Service` (`Photo Service` больше не используем), поэтому нужно в `image` `HttpRoutes` добавить вызов `JpegValidation.pipeline` при загрузке изображений (`upload`)
Других изменений в рамках данного PR не требуется

2023-11-15 20:43 UTC, stackflow commented on photo/src/main/scala/util/JPEGValidation.scala
> +object JpegValidation {
Имя файла нужно чтобы соответствовало имени класса:
`JPEGValidation.scala` <> `JpegValidation` (регистр разный у букв)
Нужно переименовать файл

2023-11-15 20:49 UTC, stackflow commented on photo/src/main/scala/api/HttpRoutes.scala
> +            .via(JpegValidation.pipeline)
Эту валидацию нужно использовать в `image` `HttpRoutes`

2023-11-19 13:01 UTC, mukhametgalin commented on photo/src/main/scala/util/JPEGValidation.scala
> +object JpegValidation {
исправил

2023-11-19 13:01 UTC, mukhametgalin commented on photo/src/main/scala/api/HttpRoutes.scala
> +            .via(JpegValidation.pipeline)
исправил, еще в коде JpegValidation поправил места, чтобы компилировалось

2023-11-19 18:45 UTC, stackflow commented on image/src/main/scala/image/api/HttpRoutes.scala
> +                List(Header("Content-Length", Files.size(path).toString))),
`List` здесь не обязателен
У `object Headers` есть метод `apply`: `def apply(headers: Header*): Headers`
Он позволяет, просто через запятую указать нужно кол-во хэдеров в ответе сервера

2023-11-19 18:46 UTC, stackflow commented on image/src/main/scala/image/api/HttpRoutes.scala
> +                List(Header("Content-Length", Files.size(path).toString))),
И вообще поле `headers` в этом `Response` лишнее
Нужно перенести `headers` в ответ для `download`, а здесь удалить
Исправь, пожалуйста

2023-11-19 19:22 UTC, mukhametgalin commented on image/src/main/scala/image/api/HttpRoutes.scala
> +                List(Header("Content-Length", Files.size(path).toString))),
поправил как получилось, потому что если делать Headers(header), то компилятор ругается на неоднозначность вызова (там видимо есть два конструктора, похожих друг на друга)

2023-11-19 19:29 UTC, stackflow approved these changes
3/3

- [x] В сервис загрузки фото добавить проверку, что загружаемое - это картинка. Можно использовать сторонее решение
- [] Также внесены изменения, для корректной работы сервсиа

2023-11-19 19:30 UTC, merged