Image service
mipt-backend-academy-winter-2023/team-3 pull request #9
Opened 2023-10-01 20:05 UTC by OvOlzhas

2023-10-15 21:17 UTC, stackflow requested changes

2023-10-15 21:17 UTC, stackflow commented on docker-compose/database.env
> +POSTGRES_USER=user
`.env` файлы не выкладываем, но можно выложить `.env.example` (уже есть в ветке `main`, чтобы было понятно как заполнять)

2023-10-15 21:17 UTC, stackflow commented on docker-compose/docker-compose.yml
> +    expose:
Для чего нужен `expose`, кажется что `ports` достаточно, чтобы открыть доступ из вне контейнера?

2023-10-15 21:17 UTC, stackflow commented on image/Dockerfile
> +RUN mkdir /opt/routing-service
Нужно переименовать `routing-service` здесь и ниже в этом файле
Это же у нас `image-service`?

2023-10-15 21:17 UTC, stackflow commented on image/src/main/resources/application.conf
> +    port = 8090
Лучше сделать через `.env` переменную, как для других сервисов

2023-10-15 21:17 UTC, stackflow commented on image/src/main/resources/application.conf
> +  image-service-config = {
Кажется не очень удачное название
Постфикс `-config` для чего, у нас и так весь файл - это конфиг
Внутри настройки для `http`, может назвать ближе к содержанию, типа `http`, `http-server` или `http-service`?

2023-10-15 21:17 UTC, stackflow commented on image/src/main/scala/image/config/Config.scala
> +  private val source = ConfigSource.default.at("app").at("image-service-config")
После правки конфига - не забудь здесь тоже ключ конфига поправить

2023-10-17 19:32 UTC, OvOlzhas commented on image/Dockerfile
> +RUN mkdir /opt/routing-service
Весь проект назвал routing service, поэтому какая то путаница

2023-10-17 19:36 UTC, OvOlzhas commented on image/src/main/resources/application.conf
> +    port = 8090
А зачем? На семинарах показывали, что так можно. Да и для других сервисов я делал также через resources/application.conf.

2023-10-17 19:37 UTC, OvOlzhas commented on image/src/main/resources/application.conf
> +    port = 8090
Это же конфигурация для сервиса, зачем ему быть переменной окружения?

2023-10-17 20:32 UTC, closed without merging